site_name: GPT Stories
theme:
  name: material
  language: "zh-TW"
  custom_dir: custom_theme/
  palette:
    - scheme: default
      primary: blue grey
      toggle:
        name: Switch to light mode
        icon: material/weather-sunny
    - scheme: slate
      primary: blue grey
      # accent: pink
      toggle:
        name: Switch to dark mode
        icon: material/weather-night
  font:
    text: Lato
  features:
    - navigation.sections
    - navigation.tracking
    - navigation.instant

plugins:
  - social:
      cards_font: Noto Sans TC
  - with-pdf:
      cover_subtitle: ChatGPT 寫的故事
      toc_title: 目錄
      # custom_template_path: custom_theme_pdf
      output_path: stories.pdf
      # debug_html: true

markdown_extensions:
  - footnotes

extra_css:
  - css/extra.css
  - css/pdf-print.css
