name: build

on:
  push:
    branches: [main]
  # GitHub Pages 要求這一條：
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache

      - name: SetLocale
        run: |
          sudo apt-get update && sudo apt-get install tzdata locales -y && sudo locale-gen zh_TW.UTF-8
          sudo localectl set-locale LANG="zh_TW.UTF-8"
          export LANG="zh_TW.UTF-8"
          sudo update-locale

      - name: Install Dependencies
        run: |
          sudo apt-get install -y fonts-arphic-ukai fonts-arphic-uming fonts-moe-standard-song fonts-moe-standard-kai
          sudo apt-get install -y fonts-noto fonts-noto-cjk fonts-noto-color-emoji fonts-noto-cjk-extra
          sudo apt-get install -y weasyprint pandoc curl
          sudo fc-cache -f -v

      - name: Install Python Packages
        run: |
          pip install pillow==9.0.0 cairosvg
          pip install -r requirements.txt

      - name: Build site
        run: mkdocs build --clean --verbose

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./site

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: pdf
          path: ./site/stories.pdf
        if: always()

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
